Class {
	#name : 'AICyclicWeightedSimpleFixture2',
	#superclass : 'Object',
	#instVars : [
		'aseCircuitWeightedGraph',
		'aseWeightedCircuitGraph',
		'negativeUnconnectedWeightedGraph',
		'negativeWeightedGraph',
		'negativeWeightedGraph2',
		'simpleWeightedGraph',
		'simpleWeightedGraph2'
	],
	#category : 'AI-Algorithms-Graph-Tests-Fixture',
	#package : 'AI-Algorithms-Graph-Tests',
	#tag : 'Fixture'
}
