"
Graph Class:
1. Cyclic
2. 3 negative Weighted, rest positive
3. Directed graphs
4. Complex Graphs
"
Class {
	#name : 'AICyclicWeightedComplexFixture',
	#superclass : 'Object',
	#instVars : [
		'complexWeightedGraph',
		'complexWeightedGraph2',
		'complexWeightedGraph3',
		'complexWeightedGraph4'
	],
	#category : 'AI-Algorithms-Graph-Tests-Fixture',
	#package : 'AI-Algorithms-Graph-Tests',
	#tag : 'Fixture'
}
